import { Link } from 'react-router-dom'
import { ArrowRight, ShieldCheck, Sparkles, FileText, Users, Download, CheckCircle2, BarChart3, Receipt } from 'lucide-react'
import SvetlanaAvatar from '../components/SvetlanaAvatar'

export default function Home() {
  return <div className="home-page overflow-hidden rounded-[32px] border border-slate-200/80 bg-white shadow-[0_24px_80px_rgba(30,41,59,.08)]">
    <section className="home-hero relative overflow-hidden px-4 pb-10 pt-6 sm:px-8 lg:px-12 lg:pb-14 lg:pt-10">
      <div className="absolute -right-24 -top-24 h-80 w-80 rounded-full bg-orange-100/80 blur-3xl"/><div className="absolute left-1/2 top-36 h-72 w-72 rounded-full bg-amber-50 blur-3xl"/>
      <div className="relative grid min-h-[620px] grid-cols-[minmax(0,1fr)_minmax(170px,46%)] items-center gap-3 sm:gap-6 lg:grid-cols-[minmax(0,1fr)_48%] lg:gap-10">
        <div className="relative z-10 min-w-0">
          <div className="mb-5 flex items-center gap-3"><img src="https://mir-samozanyatykh-api-frankfurt.onrender.com/static/logo-mir-samozanyatykh.png" alt="Мир Самозанятых" className="h-11 w-11 shrink-0 object-contain sm:h-12 sm:w-12"/><div><div className="text-[10px] font-black uppercase tracking-[.16em] text-orange-600 sm:text-xs sm:tracking-[.2em]">Мир Самозанятых</div><div className="text-[10px] text-slate-400 sm:text-xs">один аккаунт · сайт · приложение</div></div></div>
          <h1 className="max-w-3xl text-[clamp(1.8rem,4vw,3.8rem)] font-black leading-[1.02] tracking-[-.045em] text-slate-950">Всё для вашего дела.<br/><span className="brand-text">Спокойно. Умно. В одном месте.</span></h1>
          <p className="mt-5 max-w-2xl text-sm leading-6 text-slate-500 sm:text-base lg:text-lg">Доходы, клиенты, чеки, договоры и документы — в одном рабочем пространстве. А <b className="text-slate-800">Светлана</b> помогает разбираться с задачами и не терять важное.</p>
          <div className="mt-7 flex flex-wrap gap-2 sm:gap-3"><Link to="/register" className="btn-brand"><span>Начать бесплатно</span><ArrowRight className="h-4 w-4"/></Link><Link to="/svetlana" className="btn-secondary"><Sparkles className="h-4 w-4 text-orange-500"/>Светлана</Link></div>
          <div className="mt-6 hidden flex-wrap gap-x-5 gap-y-2 text-xs font-semibold text-slate-500 sm:flex"><span className="flex items-center gap-2"><CheckCircle2 className="h-4 w-4 text-emerald-500"/>Единый аккаунт</span><span className="flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-emerald-500"/>Защищённые данные</span><span className="flex items-center gap-2"><Sparkles className="h-4 w-4 text-orange-500"/>Светлана внутри</span></div>
        </div>
        <div className="relative z-10 flex h-full min-h-[520px] items-stretch justify-end">
          <div className="svetlana-hero-card relative h-full min-h-[520px] w-full overflow-hidden rounded-[28px] border border-white/10 bg-[#171a22] shadow-2xl shadow-slate-900/20 lg:min-h-[620px]">
            <div className="absolute inset-0 bg-[radial-gradient(circle_at_55%_20%,rgba(255,184,77,.26),transparent_38%),linear-gradient(145deg,#11141b,#24211b)]"/>
            <div className="absolute left-3 top-3 z-20 rounded-full border border-white/10 bg-black/20 px-2.5 py-1 text-[9px] font-bold text-white/80 backdrop-blur sm:left-5 sm:top-5 sm:px-3 sm:py-1.5 sm:text-[11px]">Светлана · локальный 3D</div>
            <div className="absolute inset-0 z-10 pt-10 sm:pt-12"><SvetlanaAvatar size="lg" interactive className="!h-full !min-h-[520px] !rounded-none !border-0 !bg-transparent !shadow-none lg:!min-h-[620px]" /></div>
            <div className="pointer-events-none absolute bottom-3 left-3 right-3 z-20 rounded-2xl border border-white/10 bg-black/35 p-3 text-white backdrop-blur-md sm:bottom-5 sm:left-5 sm:right-5 sm:p-4"><div className="font-black text-sm sm:text-base">Светлана</div><div className="mt-0.5 text-[10px] text-white/65 sm:text-xs">Ваш ИИ-ассистент · работает локально</div></div>
          </div>
        </div>
      </div>
    </section>
    <section className="grid gap-4 border-y border-slate-100 bg-slate-50/70 p-5 sm:grid-cols-2 lg:grid-cols-4 lg:p-7"><Metric title="Доходы" value="184 200 ₽" trend="+18,4%"/><Metric title="Клиенты" value="24" trend="+3 новых"/><Metric title="Чеки" value="42" trend="за месяц"/><Metric title="Документы" value="18" trend="в порядке"/></section>
    <section className="grid gap-5 p-6 sm:p-10 lg:grid-cols-[1fr_380px] lg:p-12"><div><div className="eyebrow mb-2">Всё связано</div><h2 className="text-2xl font-black tracking-tight text-slate-950 sm:text-3xl">Рабочее пространство, которое не мешает работать</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-500">Каждый инструмент находится рядом с контекстом. Не нужно переключаться между десятком сервисов.</p><div className="mt-7 grid gap-4 sm:grid-cols-2"><Feature icon={FileText} title="Документы" text="Договоры, акты и счета в одном месте."/><Feature icon={Users} title="Клиенты" text="Контакты, сделки и история общения."/><Feature icon={BarChart3} title="Финансы" text="Доходы и аналитика без сложных таблиц."/><Feature icon={Receipt} title="Чеки" text="Быстрый контроль и работа с ФНС."/></div></div><aside className="rounded-[28px] border border-orange-100 bg-gradient-to-br from-orange-50 to-amber-50 p-6"><div className="flex items-center gap-3"><SvetlanaAvatar size="md"/><div><div className="font-black text-slate-950">Светлана всегда рядом</div><div className="text-xs text-slate-500">ИИ-помощник внутри платформы</div></div></div><div className="mt-6 rounded-2xl bg-white/90 p-4 shadow-sm"><p className="text-sm leading-6 text-slate-600">«Подскажу, что сделать сегодня, помогу с документами и объясню сложное простыми словами.»</p></div><Link to="/svetlana" className="mt-4 inline-flex items-center gap-2 rounded-xl bg-orange-500 px-4 py-2.5 text-sm font-bold text-white hover:bg-orange-600">Написать Светлане <ArrowRight className="h-4 w-4"/></Link></aside></section>
    <section className="border-t border-slate-100 bg-white p-6 sm:p-10 lg:p-12"><div className="flex flex-col gap-5 rounded-[28px] border border-slate-200 bg-slate-950 p-6 text-white sm:flex-row sm:items-center sm:justify-between sm:p-8"><div><div className="text-xs font-bold uppercase tracking-[.18em] text-orange-400">Web + Android + iOS</div><h2 className="mt-2 text-2xl font-black">Ваше рабочее пространство всегда с вами</h2><p className="mt-2 text-sm text-white/60">Сайт и мобильное приложение используют одну систему.</p></div><Link to="/downloads" className="inline-flex shrink-0 items-center justify-center gap-2 rounded-xl bg-orange-500 px-5 py-3 text-sm font-bold text-white hover:bg-orange-600"><Download className="h-4 w-4"/>Скачать приложение</Link></div></section>
  </div>
}
function Metric({title,value,trend}:{title:string,value:string,trend:string}){return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="text-xs font-semibold text-slate-400">{title}</div><div className="mt-2 text-2xl font-black tracking-tight text-slate-950">{value}</div><div className="mt-1 text-xs font-bold text-orange-600">{trend}</div></div>}
function Feature({icon:Icon,title,text}:{icon:any,title:string,text:string}){return <div className="rounded-2xl border border-slate-200 bg-white p-5 transition hover:-translate-y-0.5 hover:shadow-lg hover:shadow-slate-900/5"><div className="mb-4 flex h-10 w-10 items-center justify-center rounded-xl bg-orange-50 text-orange-600"><Icon className="h-5 w-5"/></div><h3 className="font-bold text-slate-950">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{text}</p></div>}
